FROM nginx:alpine

#Remove default nginx html#
RUN rm -rf /usr/share/nginx/html/*

#Copy static site(only what we need) 
COPY index.html /usr/share/nginx/html/
COPY style.css /usr/share/nginx/html/
COPY app.js /usr/share/nginx/html/assets/
COPY assets/ /usr/share/nginx/html/assets/


EXPOSE 80
CMD ["nginx", "-g" "daemon off;"]
